### ISSUE TITLE
Wire.requestFrom() should not be followed by Wire.endTransmission().

### ISSUE THREAD

**Issue by Koepel** [hackffm/FPVCar#1]
In the file "FPVCar/arduino/FPVAutoControl/FPVAutoControl.ino" the `Wire.requestFrom()` is followed by a `Wire.endTransmission()`. That `Wire.endTransmission()` is at the moment at line 60 and may be removed.
Explanation: [Common-mistakes#2](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#2)

**Comment by vkuehn** [comment]
this has been now fixed
